# Configuration file for the template chooser
# 
# This file needs to exist in the https://github.com/DCC-EX/.github repository in the ".github/ISSUE_TEMPLATE/" folder.

blank_issues_enabled: false
contact_links:
  - name: DCC-EX Discord server
    url: https://discord.gg/y2sB4Fp
    about: For the best support experience, join our Discord server
  - name: DCC-EX Contact and Support page
    url: https://dcc-ex.com/support/index.html
    about: For other support options, refer to our Contact & Support page