# General To Do item GitHub issue form
# 
# This file needs to reside in the ".github/ISSUE_TEMPLATE/" folder.

name: To Do
description: Create a general To Do item
title: "[To Do]: "
labels:
  - To Do
body:
  - type: markdown
    attributes:
      value: |
        Use this template to create an issue for a general task that needs to be done.

        This is handy for capturing ad-hoc items that don't necessarily require code to be written or updated.
  
  - type: textarea
    id: description
    attributes:
      label: Task description
      description: Provide the details of what needs to be done.
    validations:
      required: true